#! /bin/sh -e
#
# Written by Chanop Silpa-Anan <chanop@debian.org>
#
# You have every right to do anything with this file.
# Use with care.
#

if [ $# -ne 1 ]; then
  echo "Usage:"
  echo "  $0 latexfile[.tex]"
  exit 1
fi

LATEXFILEORG=
if [ -e $1 ]; then
  LATEXFILEORG="$1"
elif [ -e $1.tex ]; then
  LATEXFILEORG="$1.tex"
else
  echo "File not found: $1[.tex]"
  exit 1
fi

echo "Found: $LATEXFILEORG"
LATEXFILENEW=`echo $LATEXFILEORG | sed -e "s/.tex/.ttex/"`
LATEXFILENAME=`echo $LATEXFILEORG | sed -e "s/.tex//"`

WORDSEG=
if which swath > /dev/null; then
  WORDSEG="swath -f latex"
elif which cttex > /dev/null; then
  WORDSEG="cttex -W"
else
  echo "Cannot find either swath or cttex"
  exit 1
fi

echo "Using: $WORDSEG for Thai word segmentation"
$WORDSEG < $LATEXFILEORG > $LATEXFILENEW
echo "Running LaTeX pass 1"
latex $LATEXFILENEW
echo "Running BibTeX"
bibtex $LATEXFILENAME
echo "Running LaTeX pass 2"
latex $LATEXFILENEW
echo "Running LaTeX pass 3"
latex $LATEXFILENEW

exit 0
